"""
Quantum Mechanics workflows for Psi4 and ORCA.
Functions to generate input files, run calculations, and parse output files.
"""

import os
import tempfile
from typing import Dict, Any, Tuple, Optional, List
import numpy as np

# Try to import psi4 and orca (if available via their Python interfaces)
try:
    import psi4
    psi4_available = True
except ImportError:
    psi4 = None
    psi4_available = False

try:
    # ORCA doesn't have a direct Python package, but we can run it as a subprocess
    import subprocess
    orca_available = True  # We assume ORCA is installed and accessible via command line
except ImportError:
    subprocess = None
    orca_available = False


def generate_psi4_input(
    molecule: Any,
    task: str = 'single_point',
    theory: str = 'b3lyp',
    basis_set: str = '6-31g*',
    charge: int = 0,
    multiplicity: int = 1,
    extra_keywords: Optional[List[str]] = None
) -> str:
    """
    Generate a Psi4 input file string.

    Parameters
    ----------
    molecule : any
        A molecule object (we assume it has attributes for coordinates, symbols, etc.)
        For simplicity, we expect a dictionary with 'symbols' and 'coordinates' (in Angstroms).
    task : str
        Type of calculation: 'single_point', 'optimization', 'frequency'.
    theory : str
        Electronic structure theory (e.g., 'b3lyp', 'hf', 'mp2').
    basis_set : str
        Basis set (e.g., '6-31g*', 'cc-pvdz').
    charge : int
        Molecular charge.
    multiplicity : int
        Spin multiplicity (1 = singlet, 2 = doublet, etc.).
    extra_keywords : list of str, optional
        Additional keywords to add to the input (e.g., ['scf_type df']).

    Returns
    -------
    str
        The Psi4 input file content.
    """
    if extra_keywords is None:
        extra_keywords = []

    # Start building the input
    lines = []
    lines.append('# Psi4 input file generated by Dynacule')
    lines.append(f'molecule mol {{')
    lines.append(f'  {charge} {multiplicity}')
    # Assuming molecule is a dict with 'symbols' and 'coordinates'
    symbols = molecule.get('symbols', [])
    coords = molecule.get('coordinates', [])
    for symbol, coord in zip(symbols, coords):
        lines.append(f'  {symbol} {coord[0]:.6f} {coord[1]:.6f} {coord[2]:.6f}')
    lines.append('}')
    lines.append('')

    # Set options
    lines.append(f'set {{')
    lines.append(f'  basis {basis_set}')
    lines.append(f'  scf_type df')  # Default to density fitting if available
    for kw in extra_keywords:
        lines.append(f'  {kw}')
    lines.append(f'}}')
    lines.append('')

    # Task-specific sections
    if task == 'single_point':
        lines.append(f'energy({theory})')
    elif task == 'optimization':
        lines.append(f'optimize({theory})')
    elif task == 'frequency':
        lines.append(f'frequency({theory})')
    else:
        raise ValueError(f'Task {task} not supported for Psi4.')

    return '\\n'.join(lines)


def generate_orca_input(
    molecule: Any,
    task: str = 'single_point',
    theory: str = 'b3lyp',
    basis_set: str = '6-31g*',
    charge: int = 0,
    multiplicity: int = 1,
    extra_keywords: Optional[List[str]] = None,
    pal: int = 1
) -> str:
    """
    Generate an ORCA input file string.

    Parameters
    ----------
    molecule : any
        A molecule object (dict with 'symbols' and 'coordinates' in Angstroms).
    task : str
        Type of calculation: 'single_point', 'optimization', 'frequency'.
    theory : str
        Electronic structure theory (e.g., 'b3lyp', 'hf', 'mp2').
    basis_set : str
        Basis set (e.g., '6-31g*', 'def2-svp').
    charge : int
        Molecular charge.
    multiplicity : int
        Spin multiplicity.
    extra_keywords : list of str, optional
        Additional keywords (e.g., ['TightSCF']).
    pal : int
        Number of processors to use.

    Returns
    -------
    str
        The ORCA input file content.
    """
    if extra_keywords is None:
        extra_keywords = []

    lines = []
    lines.append('! ' + theory + ' ' + basis_set)
    lines.append('! ' + ' '.join(extra_keywords))
    lines.append('%pal')
    lines.append(f'  nprocs {pal}')
    lines.append('end')
    lines.append('')
    lines.append('* xyzfile {charge} {multiplicity}')
    symbols = molecule.get('symbols', [])
    coords = molecule.get('coordinates', [])
    for symbol, coord in zip(symbols, coords):
        lines.append(f'  {symbol} {coord[0]:.6f} {coord[1]:.6f} {coord[2]:.6f}')
    lines.append('*')
    
    # Add task-specific blocks
    if task == 'optimization':
        lines.append('%maxiter 50')
        lines.append('%geom')
        lines.append('  Optimize')
        lines.append('end')
    elif task == 'frequency':
        lines.append('%freq')
        lines.append('  End')
        lines.append('end')
    # For single point, no extra block needed.

    return '\\n'.join(lines)


def parse_psi4_output(output_text: str) -> Dict[str, Any]:
    """
    Parse Psi4 output file to extract energies, gradients, frequencies, etc.

    Parameters
    ----------
    output_text : str
        The content of the Psi4 output file.

    Returns
    -------
    dict
        Dictionary with keys:
        - 'energy': total electronic energy (in Hartree)
        - 'gradient': gradient vector (if available, in Hartree/Bohr)
        - 'frequencies': vibrational frequencies (in cm^-1)
        - 'normal_modes': normal modes (if available)
        - 'success': boolean indicating if calculation succeeded
    """
    result = {
        'energy': None,
        'gradient': None,
        'frequencies': None,
        'normal_modes': None,
        'success': False
    }
    
    lines = output_text.split('\\n')
    
    # Look for final energy
    for line in lines:
        if 'FINAL ENERGY' in line:
            # Example: 'FINAL ENERGY: -76.0267712546'
            try:
                energy = float(line.split(':')[1].strip())
                result['energy'] = energy
                result['success'] = True
            except:
                pass
        elif 'ENERGY=' in line and 'FINAL SINGLE POINT ENERGY' in line:
            # Another common pattern
            try:
                energy = float(line.split('=')[1].strip().split()[0])
                result['energy'] = energy
                result['success'] = True
            except:
                pass
    
    # Look for gradient (if available)
    # This is more complex; we'll look for a section after 'GRADIENT' or 'CARTESIAN GRADIENT'
    # For simplicity, we'll skip detailed gradient parsing for now.
    
    # Look for vibrational frequencies
    freq_section = False
    freqs = []
    for line in lines:
        if 'VIBRATIONAL FREQUENCIES' in line:
            freq_section = True
            continue
        if freq_section:
            if 'NORMAL MODES' in line or 'IR INTENSITIES' in line:
                # End of frequency list
                break
            # Try to parse a frequency line
            parts = line.split()
            if len(parts) >= 3:
                try:
                    # First column might be mode number, second frequency, third IR intensity
                    freq = float(parts[1])
                    freqs.append(freq)
                except ValueError:
                    pass
    if freqs:
        result['frequencies'] = np.array(freqs)
    
    return result


def parse_orca_output(output_text: str) -> Dict[str, Any]:
    """
    Parse ORCA output file to extract energies, gradients, frequencies, etc.

    Parameters
    ----------
    output_text : str
        The content of the ORCA output file.

    Returns
    -------
    dict
        Dictionary with keys:
        - 'energy': total electronic energy (in Hartree)
        - 'gradient': gradient vector (if available, in Hartree/Bohr)
        - 'frequencies': vibrational frequencies (in cm^-1)
        - 'normal_modes': normal modes (if available)
        - 'success': boolean indicating if calculation succeeded
    """
    result = {
        'energy': None,
        'gradient': None,
        'frequencies': None,
        'normal_modes': None,
        'success': False
    }
    
    lines = output_text.split('\\n')
    
    # Look for final energy
    for line in lines:
        if 'FINAL SINGLE POINT ENERGY' in line:
            # Example: 'FINAL SINGLE POINT ENERGY: -76.0267712546 Eh'
            try:
                energy = float(line.split(':')[1].strip().split()[0])
                result['energy'] = energy
                result['success'] = True
            except:
                pass
        elif 'TOTAL ENERGY' in line and 'Eh' in line:
            # Sometimes appears in optimization
            try:
                energy = float(line.split(':')[1].strip().split()[0])
                result['energy'] = energy
                result['success'] = True
            except:
                pass
    
    # Look for vibrational frequencies
    freq_section = False
    freqs = []
    for line in lines:
        if 'VIBRATIONAL FREQUENCIES' in line:
            freq_section = True
            continue
        if freq_section:
            if 'NORMAL MODES' in line or 'IR INTENSITY' in line:
                break
            parts = line.split()
            if len(parts) >= 3:
                try:
                    # ORCA often prints: mode, frequency (cm^-1), IR intensity
                    freq = float(parts[1])
                    freqs.append(freq)
                except ValueError:
                    pass
    if freqs:
        result['frequencies'] = np.array(freqs)
    
    return result


def run_psi4_calculation(
    input_file: str,
    output_file: Optional[str] = None,
    scratch_dir: Optional[str] = None
) -> Tuple[bool, str]:
    """
    Run a Psi4 calculation given an input file.

    Parameters
    ----------
    input_file : str
        Path to the Psi4 input file.
    output_file : str, optional
        Path to the output file. If None, defaults to input_file with .out extension.
    scratch_dir : str, optional
        Directory for scratch files.

    Returns
    -------
    tuple (success, output_text)
        success: boolean indicating if the calculation ran without error.
        output_text: the output from the calculation (or error message).
    """
    if not psi4_available:
        return False, "Psi4 is not installed. Please install psi4 to run calculations."
    
    if output_file is None:
        output_file = os.path.splitext(input_file)[0] + '.out'
    
    # Set scratch directory if provided
    if scratch_dir:
        os.environ['PSI_SCRATCH'] = scratch_dir
    
    try:
        # Run psi4 using the Python API
        psi4.core.set_output_file(output_file, False)
        psi4.core.clean()
        psi4.core.clean_variables()
        psi4.core.clean_options()
        
        # Read the input file and execute
        with open(input_file, 'r') as f:
            input_str = f.read()
        # Use psi4 energy function? Actually, we need to parse the input to know the task.
        # For simplicity, we'll rely on the input file specifying the task.
        # We can use psi4.driver.run() but it's easier to let the input file dictate.
        # Instead, we'll run the input file as a script.
        # Note: This is a simplification; in practice, we might want to use the Python API more directly.
        exec(input_str, {'__name__': '__main__'})
        
        # Read the output file
        with open(output_file, 'r') as f:
            output_text = f.read()
        
        return True, output_text
    except Exception as e:
        return False, str(e)


def run_orca_calculation(
    input_file: str,
    output_file: Optional[str] = None,
    orca_command: str = 'orca'
) -> Tuple[bool, str]:
    """
    Run an ORCA calculation given an input file.

    Parameters
    ----------
    input_file : str
        Path to the ORCA input file.
    output_file : str, optional
        Path to the output file. If None, defaults to input_file with .out extension.
    orca_command : str
        The command to run ORCA (default 'orca', assuming it's in PATH).

    Returns
    -------
    tuple (success, output_text)
        success: boolean indicating if the calculation ran without error.
        output_text: the output from the calculation (or error message).
    """
    if output_file is None:
        output_file = os.path.splitext(input_file)[0] + '.out'
    
    # ORCA input file extension is typically .inp
    # But we can run with any extension; ORCA uses the first argument as input file.
    cmd = [orca_command, input_file]
    
    try:
        # Run ORCA and capture output
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=3600)
        output_text = result.stdout + result.stderr
        
        # Write output to file (optional)
        with open(output_file, 'w') as f:
            f.write(output_text)
        
        success = (result.returncode == 0)
        return success, output_text
    except subprocess.TimeoutExpired:
        return False, "ORCA calculation timed out."
    except Exception as e:
        return False, str(e)


# Stub for Modal.com integration

def modal_psi4_stub(
    molecule: Dict[str, Any],
    task: str = 'single_point',
    theory: str = 'b3lyp',
    basis_set: str = '6-31g*',
    charge: int = 0,
    multiplicity: int = 1
) -> Dict[str, Any]:
    """
    Stub function for Modal.com deployment for Psi4 calculations.

    Parameters
    ----------
    molecule : dict
        Dictionary with 'symbols' and 'coordinates' (in Angstroms).
    task : str
        Type of calculation.
    theory : str
        Electronic structure theory.
    basis_set : str
        Basis set.
    charge : int
        Molecular charge.
    multiplicity : int
        Spin multiplicity.

    Returns
    -------
    dict
        Dictionary containing simulation outputs.
    """
    # This is a stub. In actual Modal deployment, we would:
    # 1. Generate the input file
    # 2. Run the Psi4 calculation
    # 3. Parse the output
    # 4. Return results
    
    return {
        "status": "stub",
        "message": "This is a stub for Modal.com integration. Actual implementation would run Psi4 calculation.",
        "outputs": {}
    }


def modal_orca_stub(
    molecule: Dict[str, Any],
    task: str = 'single_point',
    theory: str = 'b3lyp',
    basis_set: str = '6-31g*',
    charge: int = 0,
    multiplicity: int = 1,
    pal: int = 1
) -> Dict[str, Any]:
    """
    Stub function for Modal.com deployment for ORCA calculations.

    Parameters
    ----------
    molecule : dict
        Dictionary with 'symbols' and 'coordinates' (in Angstroms).
    task : str
        Type of calculation.
    theory : str
        Electronic structure theory.
    basis_set : str
        Basis set.
    charge : int
        Molecular charge.
    multiplicity : int
        Spin multiplicity.
    pal : int
        Number of processors.

    Returns
    -------
    dict
        Dictionary containing simulation outputs.
    """
    return {
        "status": "stub",
        "message": "This is a stub for Modal.com integration. Actual implementation would run ORCA calculation.",
        "outputs": {}
    }


if __name__ == "__main__":
    # Example usage (for testing)
    print("QM workflows module for Psi4 and ORCA.")
    print(f"Psi4 available: {psi4_available}")
    print(f"ORCA available (assuming installed): {orca_available}")
    
    # Test input generation
    test_mol = {
        'symbols': ['H', 'H'],
        'coordinates': [[0.0, 0.0, 0.0], [0.0, 0.0, 0.74]]
    }
    psi4_inp = generate_psi4_input(test_mol, task='single_point', theory='hf', basis_set='sto-3g')
    print("\nGenerated Psi4 input:\n" + psi4_inp)
    
    orca_inp = generate_orca_input(test_mol, task='single_point', theory='hf', basis_set='sto-3g')
    print("\nGenerated ORCA input:\n" + orca_inp)